### ISSUE TITLE
send commands to repl via WebSocket

### ISSUE THREAD

**Issue by sfrieske** [jhmaster2000/bun-repl#10]
How can I send a command from a WebSocket client to the REPL, e.g. console.log(3+4) ?

**Comment by jhmaster2000** [comment]
If you run the repl with the `--debug` flag it will print out the local websocket server url at the start. The message protocol is a limited version of the V8 inspector protocol, there's unfortunately no docs for JSC's specific supported parts of it, but you may find the `bun-devtools` package on npm helpful (the repl also uses it)

**Comment by sfrieske** [comment]
Thanks for the quick reply. 
The REPL works well for me, I like especially the easy import handling. It is a long awaited feature!
