### ISSUE TITLE
Question: How does the installation works?

### ISSUE THREAD

**Issue by sengmann** [jhmaster2000/bun-repl#12]
A quick question that I couldn't find the answer by myself: How exactly does the installation work with `bun repl`? I would have expected to have to install a global package first.

Thanks for the great work!

**Comment by jhmaster2000** [comment]
You can read https://github.com/oven-sh/bun/issues/4617#issuecomment-1712469434 for information on the current state of the project including how the installation is currently working.

**Comment by sengmann** [comment]
Thanks for the quick answer. Now I do understand.
