### ISSUE TITLE
temp path is wrongly recognized

### ISSUE THREAD

**Issue by anemochore** [jhmaster2000/bun-repl#15]
I'm using win 11, and I've installed Bun today (1.1.21). When I run `bun repl`, the error occurs and it won't run:

````
error: Module not found "d:\Temp\bunx-1558969007-bun-repl@latest\node_modules\..\..\..\..\D:\Temp\bunx-1558969007-bun-repl@latest\node_modules\bun-repl\src\cli.ts"
````

My `%TEMP%` is `d:\Temp`. Obviously, `bun repl` tries to mix relative and absolute paths wrongly. Workaround is set my `%TEMP%` to some relative path like `.` or `..\` or whatever.

````
> set TEMP=.
> bun repl
> rem bun repl started without error
````

I don't know where to report to fix this trivial issue. Bun itself is running without problems. Any suggestions?

**Comment by jhmaster2000** [comment]
Do you also experience this with other CLI-based packages ran via `bunx`?

Some examples to try:
* `bunx --bun cross-env FOO=1 echo hi`
* `bunx --bun tsx`

If yes, it isn't a REPL specific bug but rather a `bunx` bug which should be reported on the Bun repository.

**Comment by anemochore** [comment]
`bunx` gives the same error. :( I'll report this to bun repo. Thank you.
