### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by iloveitaly** [jhmaster2000/bun-repl#2]
If I try to import a package installed with npm I get the following error:

```
ResolveError: Cannot find package "package-name" from /Users/mike/Projects/the-project/$bun$repl.ts
```

Any idea why? the package definitely exists and imports just fine with the node console.

**Comment by jhmaster2000** [comment]
Could you retry in the new version 1.3.3? A lot of import-related bugs have been fixed on it.

If that still doesn't work, I will need some more details:

- What is the input code for the import?
- Is the package installed globally or locally? (In advance, global packages cant be imported)
- If the package is local, is the node_modules folder in `/Users/mike/Projects/the-project/node_modules`?

**Comment by iloveitaly** [comment]
It's fixed now! Thanks!!
