### ISSUE TITLE
error: "bun-repl" exited with code 1 (SIGHUP)

### ISSUE THREAD

**Issue by abnerfs** [jhmaster2000/bun-repl#7]
Just installed bun inside a WSL today (fresh install) and I'm getting this error when running `bun repl`

```bash
error: "bun-repl" exited with code 1 (SIGHUP)
```

Saw that maybe the issue was solved in https://github.com/oven-sh/bun/issues/4617, how do I apply the fix?

**Comment by jhmaster2000** [comment]
Do you also see the `error: Failed to start server. Is port * in use?` error from the issue you linked or just the SIGHUP exit message?

**Comment by Revitate** [comment]
Me too. This is the response when I run it.
```
bash:~$ bun repl
error: "bun-repl" exited with code 1 (SIGHUP)
```
P.S. I run on WSL.

**Comment by jhmaster2000** [comment]
Can you try `bun repl --debug` and see if it outputs anything extra?

**Comment by yy77** [comment]
Same problem encountered. `bun repl --debug` will have the output as below. 

```
DEBUG: Debug mode enabled.
DEBUG: [ws/open] repl server listening on ws://localhost:60681/bun:inspect
DEBUG: REPL server initialized.
DEBUG: Transpiler initialized.
DEBUG: Trying to load REPL history from /home/mike/.bun/.bun_repl_history
DEBUG: Loading history file from /home/mike/.bun/.bun_repl_history
error: "bun-repl" exited with code 1 (SIGHUP)
```

**Comment by jhmaster2000** [comment]
Try to `rm -rf` the folder at the path given to you by running `bun pm cache` and then try re-running `bun repl`

If it still doesn't work after doing the above, also try to delete the history file at the path shown in the debug logs there, then retry.

**Comment by abnerfs** [comment]
```bash
abner@ABNER-DESKTOP:~$ bun repl --debug
DEBUG: Debug mode enabled.
DEBUG: [ws/open] repl server listening on ws://localhost:38895/bun:inspect
DEBUG: REPL server initialized.
DEBUG: Transpiler initialized.
DEBUG: Trying to load REPL history from /home/abner/.bun/.bun_repl_history
DEBUG: Loading history file from /home/abner/.bun/.bun_repl_history
error: "bun-repl" exited with code 1 (SIGHUP)
abner@ABNER-DESKTOP:~$ bun pm cache

error: MissingPackageJSON
Bun could not find a package.json file.
abner@ABNER-DESKTOP:~$ rm /home/abner/.bun/.bun_repl_history
abner@ABNER-DESKTOP:~$ bun repl --debug
DEBUG: Debug mode enabled.
DEBUG: [ws/open] repl server listening on ws://localhost:56267/bun:inspect
DEBUG: REPL server initialized.
DEBUG: Transpiler initialized.
DEBUG: Trying to load REPL history from /home/abner/.bun/.bun_repl_history
DEBUG: History file not found, creating new one at /home/abner/.bun/.bun_repl_history
DEBUG: Loading history file from /home/abner/.bun/.bun_repl_history
error: "bun-repl" exited with code 1 (SIGHUP)
abner@ABNER-DESKTOP:~$
```

**Comment by jhmaster2000** [comment]
@abnerfs @yy77 @Revitate I just released a new version (2.0.6) that should *hopefully* fix this for good this time (I remain unable to reproduce) could you all try it again now?

Something to keep in mind when you try, run it with `--debug` flag and look for the line saying something along the lines of:
```
DEBUG: REPL version v2.0.6 running on Bun v1.0.1+c3455c0ceee6bbe399781819a42fff6cf24792e2 (linux x64)
```
It should generally be the 2nd line, under the `DEBUG: Debug mode enabled.` one.

If you **don't** see that line it means your REPL version is failing to update, to fix that:
1. `rm -rf $(bun pm cache -g)` (adjust as needed if your shell does command interpolation differently)
2. `rm -rf /tmp/bun-repl@*` (adjust as needed if your temp folder is elsewhere)
Then try running `bun repl --debug` again.

**Comment by abnerfs** [comment]
It worked 🚀 , thanks

**Comment by 0x796935** [comment]
The REPL version v2.0.6 fixed my issues. (Also mentioned in this [thread](https://discord.com/channels/876711213126520882/1150861321655554100) in the bun discord)
